name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-pipeline-app:${{ github.run_number }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-pipeline-app:${{ github.run_number }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/devops-pipeline-app:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/devops-pipeline-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-pipeline-app:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name devops-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ --validate=false
          kubectl rollout status deployment/devops-app --timeout=300s
